// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: code/codes.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Atlas_Common_Code_ErrorCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case success // = 0
  case systemInvalidParams // = 10000
  case systemInternalError // = 10001
  case systemNotFound // = 10002
  case systemAlreadyExists // = 10003
  case systemUnauthorized // = 10004
  case systemForbidden // = 10005
  case systemTimeout // = 10006
  case systemTooManyRequests // = 10007
  case UNRECOGNIZED(Int)

  public init() {
    self = .success
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .success
    case 10000: self = .systemInvalidParams
    case 10001: self = .systemInternalError
    case 10002: self = .systemNotFound
    case 10003: self = .systemAlreadyExists
    case 10004: self = .systemUnauthorized
    case 10005: self = .systemForbidden
    case 10006: self = .systemTimeout
    case 10007: self = .systemTooManyRequests
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .success: return 0
    case .systemInvalidParams: return 10000
    case .systemInternalError: return 10001
    case .systemNotFound: return 10002
    case .systemAlreadyExists: return 10003
    case .systemUnauthorized: return 10004
    case .systemForbidden: return 10005
    case .systemTimeout: return 10006
    case .systemTooManyRequests: return 10007
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Atlas_Common_Code_ErrorCode] = [
    .success,
    .systemInvalidParams,
    .systemInternalError,
    .systemNotFound,
    .systemAlreadyExists,
    .systemUnauthorized,
    .systemForbidden,
    .systemTimeout,
    .systemTooManyRequests,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Atlas_Common_Code_ErrorCode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SUCCESS"),
    10000: .same(proto: "SYSTEM_INVALID_PARAMS"),
    10001: .same(proto: "SYSTEM_INTERNAL_ERROR"),
    10002: .same(proto: "SYSTEM_NOT_FOUND"),
    10003: .same(proto: "SYSTEM_ALREADY_EXISTS"),
    10004: .same(proto: "SYSTEM_UNAUTHORIZED"),
    10005: .same(proto: "SYSTEM_FORBIDDEN"),
    10006: .same(proto: "SYSTEM_TIMEOUT"),
    10007: .same(proto: "SYSTEM_TOO_MANY_REQUESTS"),
  ]
}
